import asyncio

from app.db import ensure_indexes, niches, products

PRODUCTS = [
    {"id":1,"name":"Rolo de Jade Facial","priceCost":8,"priceSell":59,"emoji":"💎","image":"https://i.ebayimg.com/images/g/eiQAAOSw~NtmQBai/s-l500.jpg","category":"Beleza & Estética","score":94,"demand":92,"competition":"Baixa","margin":68,"trend":"up","trendPct":"+87%","description":"Ferramenta de massagem facial em pedra natural, usada em rotinas de skincare para reduzir inchaço e ativar circulação. Forte apelo visual para conteúdo em vídeo.","searchVolume":"320k/mês","saturation":22,"platforms":["Shopee","Mercado Livre"],"tags":["Viral TikTok","Tendência Global"],"tips":["Grave um vídeo de uso em 15s mostrando o efeito 'antes e depois' de inchaço","Combine com um óleo facial barato para aumentar o ticket médio","Use prova social com prints de resultados de outras vendedoras"]},
    {"id":2,"name":"Fita Mouth Tape para Dormir","priceCost":3,"priceSell":29,"emoji":"😴","image":"https://i.ebayimg.com/images/g/DjMAAeSwCrhpRIUH/s-l500.jpg","category":"Beleza & Estética","score":88,"demand":81,"competition":"Média","margin":74,"trend":"up","trendPct":"+64%","description":"Fita hipoalergênica que incentiva a respiração nasal durante o sono, tendência puxada por criadores de conteúdo de biohacking e produtividade.","searchVolume":"210k/mês","saturation":35,"platforms":["Shopee","Amazon"],"tags":["Wellness","Sono"],"tips":["Eduque o público sobre respiração nasal antes de vender — produto pouco conhecido no Brasil","Ofereça kit com 30 unidades para aumentar recorrência","Use depoimentos de melhora na qualidade do sono"]},
    {"id":3,"name":"Sérum Facial com Luz LED","priceCost":15,"priceSell":89,"emoji":"✨","category":"Beleza & Estética","score":79,"demand":70,"competition":"Alta","margin":55,"trend":"stable","trendPct":"+12%","description":"Dispositivo compacto que combina sérum e luz LED vermelha para estimular colágeno. Categoria já concorrida, exige diferenciação por conteúdo.","searchVolume":"95k/mês","saturation":58,"platforms":["Shopee","Mercado Livre","Amazon"],"tags":["Skincare","Tech Beauty"],"tips":["Aposte em embalagem premium para justificar ticket mais alto","Compare com tratamentos de clínica para ancorar o preço","Foque em nicho específico (ex: acne, olheiras) em vez de 'geral'"]},
    {"id":4,"name":"Luminária de Neon Personalizada","priceCost":12,"priceSell":79,"emoji":"🌈","image":"https://i.ebayimg.com/images/g/ZMAAAOSwvp1n~4vg/s-l400.jpg","category":"Casa & Decoração","score":91,"demand":85,"competition":"Média","margin":71,"trend":"up","trendPct":"+58%","description":"Luminária de LED flexível estilo neon, alta demanda para quartos e presentes personalizados com nomes ou frases.","searchVolume":"180k/mês","saturation":40,"platforms":["Shopee","Loja Própria"],"tags":["Decoração","Presente"],"tips":["Ofereça personalização de texto — aumenta percepção de valor e reduz comparação de preço","Explore datas comemorativas (Dia dos Namorados, Natal) para picos de venda","Mostre em ambientes reais (quarto, festa) no anúncio"]},
    {"id":5,"name":"Projetor de Galáxia","priceCost":18,"priceSell":99,"emoji":"🌌","category":"Casa & Decoração","score":85,"demand":78,"competition":"Média","margin":63,"trend":"up","trendPct":"+33%","description":"Projetor que cria efeito de céu estrelado e nebulosa no teto, popular para 'setup' de quarto e vídeos ASMR/relaxamento.","searchVolume":"140k/mês","saturation":44,"platforms":["Shopee","Mercado Livre"],"tags":["Ambientação","Viral"],"tips":["Grave o ambiente escurecido para destacar o efeito visual","Associe a rotina de relaxamento e sono","Venda como kit 'home spa' com difusor de aromas"]},
    {"id":6,"name":"Difusor de Aromas USB","priceCost":10,"priceSell":55,"emoji":"🌿","category":"Casa & Decoração","score":76,"demand":68,"competition":"Alta","margin":60,"trend":"stable","trendPct":"+8%","description":"Mini difusor ultrassônico portátil, ideal para mesas de trabalho. Categoria estável, sem picos recentes de crescimento.","searchVolume":"88k/mês","saturation":61,"platforms":["Shopee","Amazon"],"tags":["Bem-estar","Home Office"],"tips":["Diferencie com design (ex: formato de vaso, animal)","Inclua óleos essenciais de brinde na primeira compra","Foque em home office como ângulo de marketing"]},
    {"id":7,"name":"Pistola de Massagem","priceCost":45,"priceSell":249,"emoji":"💪","category":"Fitness & Saúde","score":90,"demand":88,"competition":"Média","margin":66,"trend":"up","trendPct":"+45%","description":"Massageador percussivo para recuperação pós-treino, ticket médio alto e forte apelo entre praticantes de academia e corrida.","searchVolume":"165k/mês","saturation":48,"platforms":["Mercado Livre","Amazon","Loja Própria"],"tags":["Recuperação Muscular","Fitness"],"tips":["Parcerias com micro-influenciadores fitness geram credibilidade rápida","Compare o custo com sessões de massagem para justificar o preço","Ofereça garantia estendida — ticket alto exige mais confiança"]},
    {"id":8,"name":"Cinto de Postura Ergonômico","priceCost":14,"priceSell":79,"emoji":"🧍","category":"Fitness & Saúde","score":82,"demand":74,"competition":"Baixa","margin":72,"trend":"up","trendPct":"+29%","description":"Suporte ajustável para correção postural, público-alvo amplo com o crescimento do home office e dores nas costas.","searchVolume":"102k/mês","saturation":30,"platforms":["Shopee","Mercado Livre"],"tags":["Saúde","Home Office"],"tips":["Conteúdo educativo sobre postura converte melhor que anúncio direto","Ofereça guia de tamanhos claro para reduzir devoluções","Público 35+ responde bem a anúncios com linguagem de saúde"]},
    {"id":9,"name":"Tapete de Acupressão","priceCost":16,"priceSell":69,"emoji":"🧘","category":"Fitness & Saúde","score":71,"demand":60,"competition":"Média","margin":58,"trend":"down","trendPct":"-6%","description":"Tapete com pontos de acupressão para alívio de tensão nas costas, categoria em leve queda de interesse nas últimas semanas.","searchVolume":"54k/mês","saturation":52,"platforms":["Shopee"],"tags":["Relaxamento","Bem-estar"],"tips":["Monitore a queda de tendência antes de investir em estoque alto","Combine com travesseiro de acupressão em kit","Conteúdo demonstrando o uso reduz objeção de 'dói muito'"]},
    {"id":10,"name":"Carregador 3 em 1 Magnético","priceCost":22,"priceSell":99,"emoji":"⚡","image":"https://i.ebayimg.com/images/g/pv4AAeSwi69qAsqf/s-l500.jpg","category":"Tech & Gadgets","score":93,"demand":90,"competition":"Alta","margin":52,"trend":"up","trendPct":"+71%","description":"Base de carregamento sem fio para celular, fone e smartwatch simultaneamente. Alta demanda, mas também alta concorrência de preço.","searchVolume":"290k/mês","saturation":66,"platforms":["Shopee","Mercado Livre","Amazon"],"tags":["Tech","Essencial"],"tips":["Compita por qualidade/design, não só por preço — categoria já tem guerra de preço","Destaque compatibilidade com múltiplas marcas no anúncio","Vídeo comparativo de velocidade de carga gera confiança"]},
    {"id":11,"name":"Lente Clip para Celular","priceCost":9,"priceSell":49,"emoji":"📸","category":"Tech & Gadgets","score":80,"demand":72,"competition":"Média","margin":65,"trend":"stable","trendPct":"+15%","description":"Kit de lentes (macro, wide, fisheye) que acopla na câmera do celular, popular entre criadores de conteúdo iniciantes.","searchVolume":"76k/mês","saturation":38,"platforms":["Shopee"],"tags":["Fotografia Mobile","Conteúdo"],"tips":["Mostre exemplos de fotos reais tiradas com cada lente","Público de criadores de conteúdo iniciantes é o mais sensível a preço","Kit com tripé aumenta o ticket médio"]},
    {"id":12,"name":"Anel de Luz para Selfie","priceCost":11,"priceSell":54,"emoji":"💡","category":"Tech & Gadgets","score":74,"demand":65,"competition":"Alta","margin":57,"trend":"down","trendPct":"-11%","description":"Ring light portátil com clipe para celular, categoria madura e em queda de interesse com saturação alta no mercado.","searchVolume":"61k/mês","saturation":70,"platforms":["Shopee","Mercado Livre"],"tags":["Conteúdo","Influencer"],"tips":["Categoria saturada — avalie diferenciação forte antes de entrar","Foque em nicho específico (ex: dentistas, maquiadoras) em vez de público geral","Bundle com suporte de celular pode reanimar o interesse"]},
    {"id":13,"name":"Fonte Bebedouro para Pets","priceCost":28,"priceSell":129,"emoji":"🐾","category":"Pets","score":87,"demand":79,"competition":"Baixa","margin":62,"trend":"up","trendPct":"+38%","description":"Bebedouro com fluxo contínuo de água filtrada, incentiva pets a se hidratarem mais. Nicho pet com baixa concorrência direta.","searchVolume":"118k/mês","saturation":27,"platforms":["Mercado Livre","Loja Própria"],"tags":["Pet Care","Recorrente"],"tips":["Filtros de reposição geram receita recorrente pós-venda","Vídeos de pets reagindo à fonte têm alto engajamento orgânico","Destaque a redução de problemas urinários em gatos"]},
    {"id":14,"name":"Coleira GPS Inteligente","priceCost":60,"priceSell":249,"emoji":"🛰️","category":"Pets","score":83,"demand":71,"competition":"Baixa","margin":55,"trend":"up","trendPct":"+49%","description":"Coleira com rastreamento por GPS e alerta de fuga, ticket alto para tutores dispostos a pagar por segurança do animal.","searchVolume":"68k/mês","saturation":24,"platforms":["Mercado Livre","Amazon"],"tags":["Segurança Pet","Alto Ticket"],"tips":["Enfatize histórias reais de pets perdidos e encontrados","Ofereça assinatura do app de rastreamento como receita recorrente","Vídeo demonstrando o app em tempo real aumenta a conversão"]},
    {"id":15,"name":"Cubos Organizadores de Mala","priceCost":18,"priceSell":79,"emoji":"🧳","category":"Moda & Acessórios","score":78,"demand":69,"competition":"Média","margin":64,"trend":"up","trendPct":"+21%","description":"Kit de cubos compressores para organizar malas por categoria de roupa, forte apelo com a retomada de viagens.","searchVolume":"84k/mês","saturation":41,"platforms":["Shopee","Mercado Livre"],"tags":["Viagem","Organização"],"tips":["Conteúdo de 'como fazer mala' converte muito bem no formato vídeo","Venda em kits de tamanhos variados para aumentar ticket","Parcerias com criadores de conteúdo de viagem"]},
    {"id":16,"name":"Pulseira Difusora de Óleo Essencial","priceCost":6,"priceSell":39,"emoji":"📿","category":"Moda & Acessórios","score":68,"demand":55,"competition":"Alta","margin":61,"trend":"stable","trendPct":"+5%","description":"Pulseira de pedras naturais para difusão de óleos essenciais no pulso, categoria estável e madura no nicho wellness.","searchVolume":"39k/mês","saturation":63,"platforms":["Shopee"],"tags":["Wellness","Acessório"],"tips":["Combine com kit de óleos essenciais para aumentar o valor percebido","Explique o benefício de forma simples — muita gente não conhece o produto","Foque em público já engajado com wellness/yoga"]},
    {"id":17,"name":"Monitor de Temperatura para Bebê","priceCost":25,"priceSell":119,"emoji":"🌡️","category":"Kids & Baby","score":89,"demand":76,"competition":"Baixa","margin":59,"trend":"up","trendPct":"+42%","description":"Adesivo inteligente que monitora a temperatura do bebê em tempo real via app, categoria de segurança infantil com baixa concorrência.","searchVolume":"71k/mês","saturation":20,"platforms":["Mercado Livre","Amazon","Loja Própria"],"tags":["Segurança Infantil","Alto Ticket"],"tips":["Público de pais de primeira viagem é sensível a segurança, não a preço","Certificações e testes de segurança devem estar visíveis no anúncio","Depoimentos de outras mães/pais aumentam muito a confiança"]},
    {"id":18,"name":"Lampião Solar Portátil","priceCost":20,"priceSell":89,"emoji":"🏕️","category":"Outdoor & Camping","score":72,"demand":63,"competition":"Média","margin":56,"trend":"up","trendPct":"+18%","description":"Lanterna solar dobrável e recarregável, buscada por campistas e para emergências domésticas (quedas de energia).","searchVolume":"47k/mês","saturation":47,"platforms":["Shopee","Mercado Livre"],"tags":["Camping","Sustentável"],"tips":["Explore o ângulo de 'emergência em casa', não só camping — amplia o público","Teste de autonomia de bateria em vídeo gera confiança","Sazonalidade: picos em períodos de chuva/quedas de energia e feriados"]},
]

NICHES = [
    {"id":1,"name":"Beleza & Skincare","emoji":"💄","market":"R$ 2,8 bi","margin":68,"growth":34,"competition":"Média","desc":"Nicho turbinado por conteúdo de skincare no TikTok e Instagram. Produtos de baixo custo e alta percepção de valor têm o melhor desempenho.","tags":["skincare","k-beauty","autocuidado","tiktok viral"]},
    {"id":2,"name":"Casa & Decoração","emoji":"🏠","market":"R$ 1,6 bi","margin":65,"growth":27,"competition":"Média","desc":"Cresce junto com o hábito de 'setup' de ambientes para redes sociais. Itens visuais e fáceis de demonstrar em vídeo se destacam.","tags":["decoração","ambientação","presente","minimalismo"]},
    {"id":3,"name":"Fitness & Saúde","emoji":"🏋️","market":"R$ 2,1 bi","margin":63,"growth":22,"competition":"Alta","desc":"Público fiel e recorrente, mas com concorrência mais madura. Produtos de recuperação e ergonomia têm menos disputa que os genéricos.","tags":["recuperação","home gym","bem-estar","postura"]},
    {"id":4,"name":"Tech & Gadgets","emoji":"🔌","market":"R$ 3,4 bi","margin":55,"growth":19,"competition":"Alta","desc":"Maior volume de busca entre os nichos, porém margens mais apertadas por guerra de preço. Diferenciação por design é o principal ângulo.","tags":["acessórios celular","carregadores","criadores de conteúdo"]},
    {"id":5,"name":"Pets","emoji":"🐾","market":"R$ 1,2 bi","margin":60,"growth":31,"competition":"Baixa","desc":"Um dos nichos com menor concorrência direta e tutores dispostos a pagar mais por segurança e conforto do animal.","tags":["pet care","recorrência","segurança","premium"]},
    {"id":6,"name":"Moda & Acessórios","emoji":"👜","market":"R$ 1,9 bi","margin":62,"growth":15,"competition":"Alta","desc":"Nicho amplo e competitivo, com melhor performance em subnichos específicos como organização de viagem.","tags":["viagem","acessórios","autoestima"]},
    {"id":7,"name":"Kids & Baby","emoji":"👶","market":"R$ 980 mi","margin":58,"growth":24,"competition":"Baixa","desc":"Pais compram por segurança, não por preço — ticket médio mais alto e menor sensibilidade a desconto.","tags":["segurança infantil","primeiros meses","presente"]},
    {"id":8,"name":"Outdoor & Camping","emoji":"🏕️","market":"R$ 540 mi","margin":56,"growth":20,"competition":"Média","desc":"Nicho menor, mas com forte sazonalidade e bom potencial de ângulo duplo (lazer + emergência doméstica).","tags":["camping","sustentável","energia solar"]},
]


async def seed_catalog() -> None:
    await ensure_indexes()

    for p in PRODUCTS:
        await products.update_one({"id": p["id"]}, {"$set": p}, upsert=True)
    for n in NICHES:
        await niches.update_one({"id": n["id"]}, {"$set": n}, upsert=True)

    print(f"Catálogo pronto: {len(PRODUCTS)} produtos, {len(NICHES)} nichos.")


if __name__ == "__main__":
    asyncio.run(seed_catalog())
